"""Add profile_image column to emp_data table

Revision ID: ed940417a1af
Revises: 
Create Date: 2024-04-28 22:08:41.947674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed940417a1af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('emp_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.LargeBinary(), nullable=True))

    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.alter_column('empid',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.alter_column('reason',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('empid',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('emp_data', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('empid', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empid')
    )
    # ### end Alembic commands ###
